# Generated by Django 5.1.3 on 2024-11-15 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="createdAt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
